#!/usr/bin/env bash

main() {
  serve
}

serve() {
  webpack-dev-server --inline --hot
}

build() {
  NODE_ENV=production webpack --optimize-occurrence-order --optimize-dedupe
}

case "$1" in
  "" ) main ;;
  b | build ) build ;;
esac
