stages:
  - deploy
  - mirror
variables:
  GIT_SSL_NO_VERIFY: "1"


pages:
  stage: deploy
  script:
    - echo
  artifacts:
    paths:
      - public
  only:
    - master
  image: alpine

mirror:
  stage: mirror
  script:
    - git-push git@gitlab.com:gutenye/gureact.git
  image: ilyasemenov/gitlab-ci-git-push
