stages:
  - deploy
  - mirror
variables:
  GIT_SSL_NO_VERIFY: "1"

pages:
  stage: deploy
  script:
    - yarn
    - yarn run build-docs
  artifacts:
    paths:
      - public
  only:
    - docs
  image: gutenye/node

mirror:
  stage: mirror
  script:
    - git-push git@github.com:gutenye/gureact.git
  image: ilyasemenov/gitlab-ci-git-push
