stages:
  - deploy
variables:
  GIT_SSL_NO_VERIFY: "1"

mirror:
  stage: deploy
  script:
    - git-push git@gitlab.com:gutenye/gureact.git
  image: ilyasemenov/gitlab-ci-git-push

pages:
  stage: deploy
  script:
    - echo
  artifacts:
    paths:
      - public
  only:
    - master
  image: alpine
