#!/usr/bin/env bash

export PATH="node_modules/.bin:$PATH"

test() {
  (cd test && webpack-dev-server --inline)
}

build() {
  rm lib/* 2>/dev/null
  babel src -d lib --ignore __tests__
}

watch() {
  rm lib/* 2>/dev/null
  babel src -d lib --watch --ignore __tests__
}

publish() {
  version=$1
  git commit -am "publish $version"
  git tag $version
  git push
  git push --tags
}

docs() {
  styleguidist server
}

build-docs() {
  styleguidist build
}

case "$1" in
  test ) test ;;
  b | build ) build ;;
  w | watch ) watch ;;
  publish ) shift 1; publish "$@" ;;
  docs ) docs ;;
esac
