#!/usr/bin/env bash

export PATH="node_modules/.bin:$PATH"

main() {
  webpack-dev-server --inline --hot
}

build() {
  rm dist/* 2>/dev/null
  babel src -d dist
}

test() {
  (cd test && ./ake)
}

case "$1" in
  "" ) main ;;
  b | build ) build ;;
  t | test ) test ;;
esac
