// flow-typed signature: 8e0eab6af9b7bd0a27f8e25d56290218
// flow-typed version: <<STUB>>/@gutenye/babel-plugin-transform-imports_v^1.1.12/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@gutenye/babel-plugin-transform-imports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@gutenye/babel-plugin-transform-imports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@gutenye/babel-plugin-transform-imports/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module '@gutenye/babel-plugin-transform-imports/index' {
  declare module.exports: $Exports<'@gutenye/babel-plugin-transform-imports'>;
}
declare module '@gutenye/babel-plugin-transform-imports/index.js' {
  declare module.exports: $Exports<'@gutenye/babel-plugin-transform-imports'>;
}
declare module '@gutenye/babel-plugin-transform-imports/test/tests.js' {
  declare module.exports: $Exports<'@gutenye/babel-plugin-transform-imports/test/tests'>;
}
